site_name: Application-Hub context
site_description: 'Application-Hub context'
# Repository

repo_name: 'eoepca/application-hub-context'
repo_url: 'https://github.com/EOEPCA/application-hub-context'
edit_uri: 'edit/main/docs/'
site_url: 'https://eoepca.github.io/application-hub-context/'


theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list

plugins:
  - search
  - mkdocs-jupyter

nav:
  - Introduction: 'index.md'
  - Kubernetes: 'k8s.md'
  - Configuration: 'configuration.md'
  - JupyterHub API: 'jupyterhub-api.md'
  - Hands-on: 'hands-on.md'
  - Tutorial: 'tutorial.md'
